/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SDS0.5%/EDTA0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SDS0.5%/EDTA0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SDS1.0%/EDTA0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py 16C
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py 18C
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py 20C
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py 40C
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py 42C
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py 43.5C
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py 45C
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py A22-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py A22-15.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py A22-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py A22-5.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ACTINOMYCIND-10.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ACTINOMYCIND-15.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ACTINOMYCIND-2.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ACTINOMYCIND-5.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ACETATE
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ACRIFLAVINE-10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ACRIFLAVINE-2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMIKACIN-0.05
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMIKACIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMIKACIN-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMOXICILLIN-0.25
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMOXICILLIN-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMOXICILLIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMOXICILLIN-1.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMPICILLIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMPICILLIN-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMPICILLIN-4.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AMPICILLIN-8.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ANAEROBIC
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AZIDOTHYMIDINE-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AZIDOTHYMIDINE-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AZIDOTHYMIDINE-2.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AZITHROMYCIN-0.02
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AZITHROMYCIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AZITHROMYCIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BENZALKONIUM-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BENZALKONIUM-10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BENZALKONIUM-25
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BICYCLOMYCIN-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BICYCLOMYCIN-10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BILE-0.1%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BILE-0.5%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BILE-1.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BILE-2.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BLEOMYCIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BLEOMYCIN-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BLEOMYCIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BLEOMYCIN-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CCCP-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CCCP-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CCCP-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHIR090-0.02
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHIR090-0.025
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHIR090-0.04
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHIR090-0.05
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHIR090-0.075
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFOXITIN-0.25
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFOXITIN-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFOXITIN-0.75
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFOXITIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CALCOFLUOR
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CECROPINB-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CECROPINB-0.3
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFSULODIN-12.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFSULODIN-18.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFSULODIN-24.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFSULODIN-6.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CERULENIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CERULENIN-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CERULENIN-4.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CERULENIN-6.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHLOROPROMAZINE-12
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHLOROPROMAZINE-24
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHLOROPROMAZINE-3
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHLOROPROMAZINE-6
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHOLATE-0.1%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHOLATE-0.5%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHOLATE-1.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHOLATE-2.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CISPLATIN-100
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CISPLATIN-20
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CISPLATIN-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CLARYTHROMYCIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CLARYTHROMYCIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CLARYTHROMYCIN-10.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CLARYTHROMYCIN-5.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HIGHCOBALT-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HIGHCOBALT-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HIGHCOPPER-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HIGHCOPPER-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HIGHCOPPER-4.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DEOXYCHOLATE-0.1%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DEOXYCHOLATE-0.5%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DEOXYCHOLATE-2.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DIBUCAINE-0.4
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DIBUCAINE-0.8
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DIBUCAINE-1.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DOXORUBICIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DOXORUBICIN-10.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EDTA-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EDTA-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EDTA-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EGCG-20
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EGCG-5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EGCG-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EPINEPHRINE-1000
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EPINEPHRINE-250
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EPINEPHRINE-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ERYTHROMYCIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ERYTHROMYCIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ERYTHROMYCIN-10.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ERYTHROMYCIN-5.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ETHIDIUMBROMIDE-10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ETHIDIUMBROMIDE-2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ETHIDIUMBROMIDE-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py FOSFOMYCIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py FUSIDICACID-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py FUSIDICACID-20
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py FUSIDICACID-5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py FUSIDICACID-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py N-ACETYLGLUCOSAMINE
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py GLUFOSFOMYCIN-0.05
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py GLUFOSFOMYCIN-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py GLUCOSAMINE
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py GLUCOSE
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py GLYCEROL
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HYDROXYUREA-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HYDROXYUREA-10.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HYDROXYUREA-5.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py INDOLICIDIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ISONIAZID-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ISONIAZID-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ISONIAZID-1.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py LEVOFLOXACIN-0.002
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MMS-0.05%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MALTOSE
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MECILLINAM-0.03
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MECILLINAM-0.06
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MECILLINAM-0.09
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MECILLINAM-0.12
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py METHOTREXATE-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py METHOTREXATE-25
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MINOCYCLINE-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MINOCYCLINE-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MINOCYCLINE-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py MITOMYCINC-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NH4CL
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HIGHNICKEL-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HIGHNICKEL-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NIGERICIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NIGERICIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NIGERICIN-5.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NITROFURANTOIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NITROFURANTOIN-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NITROFURANTOIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NITROFURANTOIN-1.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NITROFURANTOIN-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NOREPINEPHRINE-100
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NOREPINEPHRINE-1000
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PROPIDIUMIODIDE-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PROPIDIUMIODIDE-20
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PROPIDIUMIODIDE-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PMS-0.02
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PMS-0.05
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PMS-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PARAQUAT-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PARAQUAT-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PARAQUAT-10.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PARAQUAT-18.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PARAQUAT-5.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PEROXIDE-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PEROXIDE-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PEROXIDE-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PEROXIDE-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PHLEOMYCIN-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PHLEOMYCIN-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PHLEOMYCIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PROCAINE-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PROCAINE-10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PROCAINE-30
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PROCAINE-5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PUROMYCIN-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PUROMYCIN-25
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PUROMYCIN-5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PYOCYANIN-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PYOCYANIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PYOCYANIN-10.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py RADICICOL-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py RADICICOL-10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py RADICICOL-5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SDS-0.5%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SDS-1.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SDS-2.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SDS-3.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SDS-4.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py STREPTOMYCIN-0.05
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py STREPTONIGRIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py STREPTONIGRIN-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py STREPTONIGRIN-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SUCCINATE
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SULFAMONOMETHOXINE-100
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SULFAMONOMETHOXINE-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TAUROCHOLATE-0.1%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TAUROCHOLATE-0.5%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TAUROCHOLATE-1.0%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py THEOPHYLLINE-10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py THEOPHYLLINE-100
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py THIOLACTOMYCIN-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py THIOLACTOMYCIN-5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py THIOLACTOMYCIN-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TOBRAMYCIN-0.05
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TOBRAMYCIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TOBRAMYCIN-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TOBRAMYCIN-0.4
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TRICLOSAN-0.05
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TRITONX-0.01%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TRITONX-0.03%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TRITONX-0.2%
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TUNICAMYCIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TUNICAMYCIN-3.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TUNICAMYCIN-7.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py VANCOMYCIN-10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py VANCOMYCIN-20
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py VANCOMYCIN-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py VERAPAMIL-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py VERAPAMIL-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py VERAPAMIL-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AZTREONAM-0.02
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py AZTREONAM-0.04
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BACITRACIN-100
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BACITRACIN-200
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py BACITRACIN-300
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CARBENICILLIN-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CARBENICILLIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CARBENICILLIN-1.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFSULODIN-6.0,MECILLINAM-0.03
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFACLOR-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFACLOR-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFACLOR-3.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFTAZIDIME-0.025
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFTAZIDIME-0.05
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CEFTAZIDIME-0.075
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHLORAMPHENICOL-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHLORAMPHENICOL-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHLORAMPHENICOL-1.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CHLORAMPHENICOL-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CIPROFLOXACIN-0.004
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CIPROFLOXACIN-0.006
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CIPROFLOXACIN-0.008
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py CYCLOSERINED-16
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DOXYCYCLINE-0.25
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DOXYCYCLINE-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DOXYCYCLINE-0.75
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py DOXYCYCLINE-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EGTA-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EGTA-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EGTA-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py EGTA-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ETHANOL-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ETHANOL-4.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py ETHANOL-6.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py GENTAMICIN-0.05
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py GENTAMICIN-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py HIGHFE
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py LOWFE
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NACL-150
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NACL-300
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NACL-450
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NACL-600
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NALIDIXICACID-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NALIDIXICACID-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NALIDIXICACID-1.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NALIDIXICACID-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NORFLOXACIN-0.01
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NORFLOXACIN-0.02
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NORFLOXACIN-0.04
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NOVOBIOCIN-10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NOVOBIOCIN-12
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NOVOBIOCIN-30
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NOVOBIOCIN-4
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NOVOBIOCIN-6
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py NOVOBIOCIN-8
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py OXACILLIN-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py OXACILLIN-40.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py OXACILLIN-5.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PH10
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PH4
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PH4.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PH5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PH6
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PH8
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PH9
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py PH9.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py POLYMYXINB-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py POLYMYXINB-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py POLYMYXINB-4.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py POLYMYXINB-6.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py RIFAMPICIN-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py RIFAMPICIN-2.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SPECTINOMYCIN-4.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SPECTINOMYCIN-6.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SPIRAMYCIN-1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SPIRAMYCIN-20
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SPIRAMYCIN-5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SULFAMETHIZOLE-100
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SULFAMETHIZOLE-200
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py SULFAMETHIZOLE-300
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TETRACYCLINE-0.25
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TETRACYCLINE-0.5
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TETRACYCLINE-0.75
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TETRACYCLINE-1.0
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TRIMETHOPRIM-0.1
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TRIMETHOPRIM-0.2
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TRIMETHOPRIM-0.3
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TRIMETHOPRIM-0.4
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py TRIMETHOPRIM-0.1,SULFAMETHIZOLE-50
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py UV-12SEC
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py UV-18SEC
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py UV-24SEC
/cbrc/software/anaconda/v2.1.0.app/bin/python ./Ecoli_FVA.py UV-6SEC
